# Generated by Django 2.2.4 on 2019-09-19 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='membership',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
