# Generated by Django 2.2.4 on 2019-09-25 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('pick', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('content', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pick.Pick')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Accounts')),
            ],
            options={
                'db_table': 'pick_comments',
            },
        ),
    ]
