# Generated by Django 2.2.4 on 2019-09-26 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_auto_20190919_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('phone_number', models.CharField(max_length=16)),
                ('special_request', models.TextField(blank=True, max_length=512)),
                ('booking_id', models.AutoField(db_column='Booking_ID', primary_key=True, serialize=False)),
                ('is_vacancy', models.BooleanField(default=True, verbose_name='Room Availability')),
                ('check_in', models.DateField(max_length=10, verbose_name='Check-In Date')),
                ('check_out', models.DateField(max_length=10, verbose_name='Check-Out Date')),
                ('currency', models.CharField(default='KRW', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='account.Accounts', verbose_name='In the name of')),
            ],
            options={
                'db_table': 'booking',
                'managed': True,
            },
        ),
    ]
