# Generated by Django 2.2.4 on 2019-09-26 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0003_auto_20190920_1551'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'payment',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='booking',
            name='booking_id',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='currency',
        ),
        migrations.AddField(
            model_name='booking',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='place.Place'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_in',
            field=models.DateField(max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out',
            field=models.DateField(max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='account.Accounts'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='is_vacancy',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='special_request',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.Payment'),
        ),
    ]
