# Generated by Django 2.2.4 on 2019-09-17 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Magazines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_image_url', models.URLField(max_length=400)),
                ('title_text_image_url', models.URLField(max_length=400)),
                ('identifier', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('intro', models.CharField(max_length=100)),
                ('main_image_url', models.URLField(max_length=400)),
                ('footer_image_url', models.URLField(max_length=400)),
                ('link_btn_title', models.CharField(max_length=100, null=True)),
                ('link_btn_url', models.URLField(max_length=400)),
                ('logo_url', models.URLField(max_length=400)),
                ('publish_title', models.CharField(max_length=100)),
                ('video_link', models.URLField(max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'magazines',
            },
        ),
        migrations.CreateModel(
            name='Contents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('magazine_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='magazines.Magazines')),
            ],
            options={
                'db_table': 'contents',
            },
        ),
    ]
