# Generated by Django 2.2.4 on 2019-09-17 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazines',
            name='link_btn_url',
            field=models.URLField(max_length=400, null=True),
        ),
    ]
