# Generated by Django 2.2.4 on 2019-09-17 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0002_auto_20190917_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazines',
            name='video_link',
            field=models.URLField(max_length=400, null=True),
        ),
    ]
