# Generated by Django 2.2.4 on 2019-09-18 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0003_auto_20190917_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magazines',
            name='publish_title',
        ),
        migrations.RemoveField(
            model_name='magazines',
            name='video_link',
        ),
        migrations.AlterField(
            model_name='magazines',
            name='footer_image_url',
            field=models.URLField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='magazines',
            name='intro',
            field=models.CharField(max_length=200),
        ),
    ]
