# Generated by Django 2.2.4 on 2019-09-18 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0004_auto_20190918_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='contents',
            name='Headers',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contents',
            name='image_url',
            field=models.URLField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='contents',
            name='magazine_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazines.Magazines'),
        ),
    ]
