# Generated by Django 2.2.4 on 2019-09-18 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0006_auto_20190918_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contents',
            name='Headers',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contents',
            name='magazine_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazines.Magazines'),
        ),
    ]
