# Generated by Django 2.2.4 on 2019-09-18 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0007_auto_20190918_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contents',
            old_name='Headers',
            new_name='header',
        ),
        migrations.RenameField(
            model_name='contents',
            old_name='magazine_id',
            new_name='magazine',
        ),
    ]
