# Generated by Django 2.2.4 on 2019-09-21 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0011_auto_20190920_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazines',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='place.Place'),
        ),
    ]
