# Generated by Django 2.2.4 on 2019-09-21 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0012_auto_20190921_0001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magazines',
            name='place',
        ),
    ]
