# Generated by Django 2.2.4 on 2019-09-24 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0022_magazines_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazines',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='place.Place'),
        ),
    ]
