# Generated by Django 2.2.4 on 2019-09-25 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenities', models.CharField(max_length=100, null=True, unique=True)),
            ],
            options={
                'db_table': 'amenity',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('features', models.CharField(max_length=100, null=True, unique=True)),
            ],
            options={
                'db_table': 'feature',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('full_address', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=10)),
                ('street', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=10)),
                ('province', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('longitude', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('website', models.URLField(max_length=2500, null=True)),
                ('facebook', models.URLField(max_length=2500, null=True)),
                ('instagram', models.URLField(max_length=2500, null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('price_min', models.DecimalField(decimal_places=1, max_digits=9)),
                ('price_max', models.DecimalField(decimal_places=1, max_digits=9)),
                ('persons_min', models.PositiveSmallIntegerField()),
                ('persons_max', models.PositiveSmallIntegerField()),
                ('is_vacancy', models.BooleanField(default=True, null=True)),
                ('room_capacity', models.PositiveSmallIntegerField()),
                ('check_in', models.CharField(max_length=10)),
                ('check_out', models.CharField(max_length=10)),
                ('place_type', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amenities', models.ManyToManyField(blank=True, to='place.Amenity')),
                ('features', models.ManyToManyField(blank=True, to='place.Feature')),
            ],
            options={
                'db_table': 'place',
            },
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('styles', models.CharField(max_length=100, null=True, unique=True)),
            ],
            options={
                'db_table': 'style',
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targets', models.CharField(max_length=100, null=True, unique=True)),
            ],
            options={
                'db_table': 'target',
            },
        ),
        migrations.CreateModel(
            name='Tourspot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tourspots', models.CharField(max_length=100, null=True, unique=True)),
            ],
            options={
                'db_table': 'tourspot',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('room_type', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('detail', models.CharField(max_length=500)),
                ('place_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='place.Place')),
            ],
            options={
                'db_table': 'rooms',
            },
        ),
        migrations.AddField(
            model_name='place',
            name='styles',
            field=models.ManyToManyField(blank=True, to='place.Style'),
        ),
        migrations.AddField(
            model_name='place',
            name='targets',
            field=models.ManyToManyField(blank=True, to='place.Target'),
        ),
        migrations.AddField(
            model_name='place',
            name='tourspots',
            field=models.ManyToManyField(blank=True, to='place.Tourspot'),
        ),
    ]
