# Generated by Django 2.2.4 on 2019-09-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_auto_20190919_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='persons_max',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='place',
            name='persons_min',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='place',
            name='price_max',
            field=models.DecimalField(decimal_places=1, max_digits=9),
        ),
        migrations.AlterField(
            model_name='place',
            name='price_min',
            field=models.DecimalField(decimal_places=1, max_digits=9),
        ),
        migrations.AlterField(
            model_name='place',
            name='room_capacity',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
